### PR TITLE
Adapt to module system

### PR DESCRIPTION
**Pull request by johanneskoester**
@vsoch this is a quite extensive rewrite of snakedeploy to comply with the new [Snakemake module system](https://slides.com/johanneskoester/snakemake-6). I hope you don't mind. The new module system makes it super easy to deploy workflows, so much of the previously needed functionality is obsolete now. Nevertheless, your codebase has helped a lot to quickly set this up. Please let me know what you think before I merge this.

### CODE REVIEW

**Comment by vsoch** [comment]
@johanneskoester totally okay, and exciting! I was just going to suggest to remove the python testing since the file was removed - I think you'll still need to install snakedeploy to the environment first (the recent error).

I've been busy with my new role, but still have time in weekends / evenings so if there is something I can come back and help with, please let me know! One thing I've been trying to think about is how we can better combine package managers (e.g., something like spack, or something like the autumus registry or [singularity registry hpc](singularity-hpc.readthedocs.io/) that exposes any container to be available with environment modules / LMOD with workflow managers. The worlds seem pretty separate at the moment, and I'm wondering if we can do better. E.g., there are a ton of users of spack, and it has every piece of scientific software you could image - could snakemake be used alongside it?

**Comment by johanneskoester** [comment]
> @johanneskoester totally okay, and exciting! I was just going to suggest to remove the python testing since the file was removed - I think you'll still need to install snakedeploy to the environment first (the recent error).
> 
> I've been busy with my new role, but still have time in weekends / evenings so if there is something I can come back and help with, please let me know! One thing I've been trying to think about is how we can better combine package managers (e.g., something like spack, or something like the autumus registry or [singularity registry hpc](singularity-hpc.readthedocs.io/) that exposes any container to be available with environment modules / LMOD with workflow managers. The worlds seem pretty separate at the moment, and I'm wondering if we can do better. E.g., there are a ton of users of spack, and it has every piece of scientific software you could image - could snakemake be used alongside it?

Hi Vanessa, great to hear that! Yes, spack is something that could be easily integrated into snakemake as well. I think there is no reason to exclude it, since we already have conda, singularity, and env modules.

**Comment by vsoch** [comment]
@tgamblin what do you think? 

> Hi Vanessa, great to hear that! Yes, spack is something that could be easily integrated into snakemake as well. I think there is no reason to exclude it, since we already have conda, singularity, and env modules.

Snakemake is a huge community - mostly biology oriented, but there is great overlap in spack packages with what is needed here. It would be fairly straight forward to add spack support to snakemake, although I suspect we'd want to use binary packages instead of building from source so it's not too slow. If that's not ready / doable now, it should be in the near future?

**Comment by tgamblin** [comment]
I'm in favor -- I think it's a great idea.  I think Snakemake could potentially simplify some current Spack users' workflows, e.g. look at http://pantheonscience.org/e4s/.  There's stuff being orchestrated there that is outside Spack, but they use Spack to deploy the software stacks from a build cache.

Ideally you could use Spack either from-source, with a binary cache, or both (i.e. build on first run or on change, fetch from cache until things change again).  Spack is supposed to be transparent about this so either could fit.

Anyway yes!  Sounds great to me.

**Comment by johanneskoester** [comment]
Happy to discuss this further, also to help with reviewing any contributions. Just my personal time is too limited to do this myself, sorry.

**Comment by vsoch** [comment]
@johanneskoester totally understand - it's something I was thinking about when I was joining my new role, and hoping to get back to. Another idea was having [flux](https://github.com/flux-framework/flux-core) as an executor although I'm not on the team for that projecty. I think we would need to find interest on our side, and then it's something I could pursue. I will look into it!

**Pull request merged**
